---
l2_interfaces:
  cs1:
  - name: GigabitEthernet0/1
    description: access1
    mode: trunk
  - name: GigabitEthernet0/2
    description: access2
    mode: trunk
  - name: GigabitEthernet0/3
    description: cs2
    mode: trunk
  cs2:
  - name: GigabitEthernet0/1
    description: access1
    mode: trunk
  - name: GigabitEthernet0/2
    description: access2
    mode: trunk
  - name: GigabitEthernet0/3
    description: cs1
    mode: trunk
  access1:
  - name: GigabitEthernet0/1
    description: cs1
    mode: trunk
  - name: GigabitEthernet0/2
    description: cs2
    mode: trunk
  access2:
  - name: GigabitEthernet0/1
    description: cs1
    mode: trunk
  - name: GigabitEthernet0/2
    description: cs2
    mode: trunk

vlans:
- name: DMZ
  vlan_id: 10
- name: APP
  vlan_id: 20
- name: DATA
  vlan_id: 30

