---
l2_interfaces:
  cs1:
  - name: GigabitEthernet0/1
    description: access1
    mode: trunk
  - name: GigabitEthernet0/2
    description: access2
    mode: trunk
  - name: GigabitEthernet0/3
    description: cs2
    mode: trunk
  cs2:
  - name: GigabitEthernet0/1
    description: access1
    mode: trunk
  - name: GigabitEthernet0/2
    description: access2
    mode: trunk
  - name: GigabitEthernet0/3
    description: cs1
    mode: trunk
  access1:
  - name: GigabitEthernet0/1
    description: cs1
    mode: trunk
  - name: GigabitEthernet0/2
    description: cs2
    mode: trunk
  - name: GigabitEthernet2/0
    description: dmz
    mode: access
    vlan: 10
  access2:
  - name: GigabitEthernet0/1
    description: cs1
    mode: trunk
  - name: GigabitEthernet0/2
    description: cs2
    mode: trunk
  - name: GigabitEthernet2/0
    description: app
    mode: access
    vlan: 20
  - name: GigabitEthernet2/1
    description: data
    mode: access
    vlan: 30

vlans:
- name: DMZ
  vlan_id: 10
- name: APP
  vlan_id: 20
- name: DATA
  vlan_id: 30
- name: VOICE
  vlan_id: 99

