---
l2_interfaces:
  core01:
    - name: GigabitEthernet0/1
      description: access01
      mode: trunk
    - name: GigabitEthernet0/2
      description: access02
      mode: trunk
    - name: GigabitEthernet0/3
      description: core02
      mode: trunk
  core02:
    - name: GigabitEthernet0/1
      description: access01
      mode: trunk
    - name: GigabitEthernet0/2
      description: access02
      mode: trunk
    - name: GigabitEthernet0/3
      description: core01
      mode: trunk
  access01:
    - name: GigabitEthernet0/1
      description: core01
      mode: trunk
    - name: GigabitEthernet0/2
      description: core02
      mode: trunk
  access02:
    - name: GigabitEthernet0/1
      description: core01
      mode: trunk
    - name: GigabitEthernet0/2
      description: core02
      mode: trunk