Ansible_network_os: ios
Ansible_connection: network_cli
Ansible_user: lab
Ansible_password: cisco
Ansible_become: yes
Ansible_become_password: cisco
Ansible_become_method: enable

ntp_server: 172.20.1.17

dns_servers:
- 172.20.1.250
- 172.29.1.251
