ansible_network_os: ios
ansible_connection: network_cli
ansible_user: lab
ansible_password: cisco
ansible_become: yes
ansible_become_password: cisco
ansible_become_method: enable

domain_name: devnet.io

ntp_server: 172.20.1.17

dns_servers:
- 172.20.1.250
- 172.29.1.251
