---
- name: show run
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: show run
      cisco.ios.ios_command:
        commands:
        - show run
      register: print_output

    - debug: var=print_output

    - name: save output to a file
      copy: content="{{ print_output.stdout }}" dest="./output/{{ inventory_hostname }}.txt"
