---
- name: show run
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: show run
      iosxr_command:
        authorize: yes
        commands:
          - show run

      register: print_output

    - debug: var=print_output.stdout_lines

    - name: save output to a file
      copy: content="{{ print_output.stdout }}" dest="./output/{{ inventory_hostname }}.txt"
