---
- name: "Play1: Configure All LAN Switches"
  hosts: lan
  gather_facts: yes
  tags: lan
  tasks:
  - name: "Configure Hostname and Domain Name"
    cisco.ios.ios_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: "{{ domain_name }}"
      lookup_enabled: no
      name_servers: "{{ dns_servers }}"
  - name: "Configure NTP"
    cisco.ios.ios_ntp:
      server: "{{ ntp_server }}"
      logging: true
      state: present
      key_id: "10"
      auth_key: 15435A030726242723273C21181319000A
      auth: true
  - name: Get Running Config
    cisco.ios.ios_command:
      commands:
      - sh run
    register: running_config
  
  - name: Get Current List of NTP Servers
    set_fact: ntp_servers_in_cfg="{{ running_config.stdout[0] | regex_findall('^ntp server (\S+)', multiline=True) }}"

  - name: Remove Old NTP Servers
    ios_config:
      lines:
      - "no ntp server {{ item }}"
    when: item != ntp_server
    loop: "{{ ntp_servers_in_cfg }}"

  - name: "Configure Interfaces"
    cisco.ios.ios_interfaces:
      config:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        duplex: "{{ intf_duplex }}"
        mtu: "{{ intf_mtu }}"
        enabled: yes
      state: merged
      loop: "{{ l2_interfaces[inventory_hostname] }}"
    register: ios_intf
    tags: interfaces


