---
- name: "Play1: Configure All LAN Switches"
  hosts: lan
  gather_facts: no
  tags: lan
  tasks:
  - name: "Configure Hostname and Domain Name"
    cisco.ios.ios_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: "{{ domain_name }}"
      lookup_enabled: no
      name_servers: "{{ dns_servers }}"
  - name: "Configure NTP"
    cisco.ios.ios_ntp:
      server: "{{ ntp_server }}"
      logging: true
      state: present
      key_id: "10"
      auth_key: 15435A030726242723273C21181319000A
      auth: true



